plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'
    implementation 'io.github.bonigarcia:webdrivermanager:5.8.0'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.3.2'
    implementation 'org.slf4j:slf4j-api:2.0.9'                     // SLF4J API
    implementation 'ch.qos.logback:logback-classic:1.4.11'        // 실제 출력 구현체
    implementation 'org.json:json:20231013'
    implementation 'org.jsoup:jsoup:1.15.4'
}

application {
    mainClass = 'api.selenium.crawlerApi'
    applicationDefaultJvmArgs = [
        "-DDB_PASSWORD=${project.findProperty('dbPassword')}"
    ]
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

